<?php 
session_start();
function email()
{
    if(!empty($_POST["subject"])&&!empty($_POST["message"]))
    {
        $to="youremail@gmail.com";
        $subject= $_POST["subject"]; 
        $message= $_POST["message"];
        $from = $_SESSION["email"];
        $headers = "From:" . $from;
                if(mail($to,$subject,$message,$headers))
                {
                    $to=$_SESSION["email"];
                    $subject= "Auto Acknowledgement"; 
                    $message= "Dear Customer,

Thank you for writing to HCSTutorials. This is an automated response to your e-mail. We will respond to you within 1-2 working days.

Create your Account today at https://localhost/phpproj1c/index.php.
 
Happy to help,

HCSTUTORIALS Care
";
                    $from = "acknowledgements@youremail.com";
                    $headers = "From:" . $from;
                    if(mail($to, $subject, $message, $headers))
                    {//echo 'An Autogenerated mail has ben sent<br>Please check your mail!!<br>';
                   // header("Location:details.php");
                    echo "<script>alert('An Autogenerated mail has ben sent<br>Please check your mail!!')</script>";
                    echo("<meta http-equiv=\"refresh\" content=\"0;URL='nsendemail.php'\">");
                    }else{
                       // echo 'We are facing a problem right now we will contact you shortly!!';
                        echo "<script>alert('We are facing a problem right now we will contact you shortly!!')</script>";
                        echo("<meta http-equiv=\"refresh\" content=\"0;URL='nsendemail.php'\">");
                    }
                }else {
            //echo 'Email could not be sent. Try after some time';
            echo "<script>alert('Email could not be sent. Try after some time')</script>";
            echo("<meta http-equiv=\"refresh\" content=\"0;URL='nsendemail.php'\">");
        }
            }else{
                //echo 'Please fill in all the fields';
                echo "<script>alert('Please fill in all the fields')</script>";
                echo("<meta http-equiv=\"refresh\" content=\"0;URL='nsendemail.php'\">");
            }
            include 'nsendemail.php';
        }
        if(isset($_POST['submit']))
        {
            email();
        }
        
 ?>